### PR TITLE
compressing all the images

### PR DESCRIPTION
**Pull request by origamifreak2**
Passed all the images through some compression software https://imageoptim.com/mac . The quality of the images should not be affected.

### CODE REVIEW

**Comment by origamifreak2** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by origamifreak2** [comment]
recheck

**Comment by origamifreak2** [comment]
recheck

**Comment by sgenoud** [comment]
Thanks for the PR! I will look into fixing this CLA bot. This is a PITA.

Nevertheless I have an additional request. You have compressed all the images - even the ones in the tests (which should be kept as is). You would mind reverting this part of the PR (I can also do it myself).

**Comment by origamifreak2** [comment]
@sgenoud No problem, I've reverted all the images in the tests folder.

**Comment by origamifreak2** [comment]
recheck

**Comment by sgenoud** [comment]
Did you try to rebase main (I hope it helps with the CLA issue, it is a pain, sorry)

**Comment by origamifreak2** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by origamifreak2** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by origamifreak2** [comment]
recheck

**Comment by sgenoud** [comment]
After some investigation into why the CLA checks was not working I think I have found the issue.

I think that the email you used with `git` itself is not registered as one of your emails for @origamifreak2, but for another github account @camden-bassett . Could you merge your accounts, or sign with the @camden-bassett account?

Sorry for these complications!

**Comment by origamifreak2** [comment]
recheck

**Pull request merged**
