### PR TITLE
Fix typo in demo url

### PR DESCRIPTION
**Pull request by Misiur**

### CODE REVIEW

**Comment by sgenoud** [comment]
recheck

**Comment by sgenoud** [comment]
Can you sign the CLA for this PR? It is not big but I'd like for you to be an official contributor!

**Comment by Misiur** [comment]
_I have read the CLA Document and I hereby sign the CLA_

**Comment by Misiur** [comment]
recheck

**Comment by sgenoud** [comment]
Thanks for the PR!

**Pull request merged**
